on:
  push:
    branches: [main]
  pull_request:

name: R-CMD-check

permissions: read-all

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'release'}
          - {os: ubuntu-latest,   r: 'oldrel-1'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      # Step 1: Check out the code
      - uses: actions/checkout@v4

      # Step 2: Set TAR options to suppress warnings
      - name: Set TAR options to suppress warnings
        run: echo "TAR=tar --no-same-owner" >> $GITHUB_ENV

      # Step 3: Set up Pandoc
      - uses: r-lib/actions/setup-pandoc@v2

      # Step 4: Set up R
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      # Step 5: Set up Python
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'  # Specify Python version

      # Step 6: Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy tensorflow keras

      # Step 7: Set up R dependencies
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      # Step 8: Check the R package
      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
